// src/pages/apartmentsData.jsx
export const curatedApartmentsAndHouses = [
  {
    _id: 'apt-1',
    title: 'The Grand Royale Skyline Apartment',
    location: 'Mumbai, Maharashtra',
    price: 65000000,
    propertyType: 'Apartment',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 3,
    bathrooms: 3,
    floorSpace: '2,800',
    description: 'An immaculate luxury apartment overlooking the Arabian Sea, featuring Italian marble tiling, modular designer kitchen, and private deck space.'
  },
  {
    _id: 'apt-2',
    title: 'Emerald Heritage Independent House',
    location: 'Bengaluru, Karnataka',
    price: 85000000,
    propertyType: 'Independent House',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 4,
    bathrooms: 4,
    floorSpace: '4,200',
    description: 'A quiet, independent residential haven nestled in a prime Bengaluru neighborhood, complete with a private lawn and parking pavilion.'
  },
  {
    _id: 'apt-3',
    title: 'The Metropolis Luxury Suite',
    location: 'Gurugram, Haryana',
    price: 52000000,
    propertyType: 'Apartment',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 3,
    bathrooms: 3,
    floorSpace: '2,400',
    description: 'Ultra-modern high-rise living with full concierge service, clubhouse access, and breathtaking skyline illumination views.'
  },
  {
    _id: 'apt-4',
    title: 'Lotus Grand Independent Villa-House',
    location: 'Hyderabad, Telangana',
    price: 92000000,
    propertyType: 'Independent House',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 4,
    bathrooms: 5,
    floorSpace: '4,800',
    description: 'Spacious independent home featuring multi-level balconies, private rooftop terrace, and high-security gated compound architecture.'
  },
  {
    _id: 'apt-5',
    title: 'The Residency Skyline Flat',
    location: 'Kolkata, West Bengal',
    price: 45000000,
    propertyType: 'Apartment',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 3,
    bathrooms: 2,
    floorSpace: '2,100',
    description: 'Classic elegance blended with modern apartment utilities near the heart of Kolkata cultural districts.'
  },
  {
    _id: 'apt-6',
    title: 'Azure Coast Independent Duplex',
    location: 'Goa, India',
    price: 78000000,
    propertyType: 'Independent House',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 4,
    bathrooms: 4,
    floorSpace: '3,900',
    description: 'A gorgeous independent beachside duplex with open verandas and cooling sea breezes.'
  },
  {
    _id: 'apt-7',
    title: 'The Grand Vista Urban Apartment',
    location: 'Pune, Maharashtra',
    price: 49000000,
    propertyType: 'Apartment',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 3,
    bathrooms: 3,
    floorSpace: '2,300',
    description: 'Contemporary smart-home apartment with energy-efficient fixtures and panoramic hill views.'
  },
  {
    _id: 'apt-8',
    title: 'Royal Oak Independent Estate',
    location: 'Chennai, Tamil Nadu',
    price: 88000000,
    propertyType: 'Independent House',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 5,
    bathrooms: 5,
    floorSpace: '5,000',
    description: 'A stately independent home combining traditional South Indian architectural courtyards with luxury modern living.'
  },
  {
    _id: 'apt-9',
    title: 'The Apex Skyline Residence',
    location: 'Ahmedabad, Gujarat',
    price: 58000000,
    propertyType: 'Apartment',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 3,
    bathrooms: 3,
    floorSpace: '2,600',
    description: 'High-end executive apartment featuring acoustic insulation and premium designer fittings.'
  }
];