// src/pages/propertiesData.js
export const curatedVillasAndPenthouses = [
  {
    _id: 'villa-1',
    title: 'The Azure Horizon Luxury Villa',
    location: 'Goa, India',
    price: 185000000,
    propertyType: 'Luxury Villa',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 5,
    bathrooms: 6,
    floorSpace: '6,200',
    description: 'Experience absolute coastal luxury at The Azure Horizon. Located along the pristine shores of Goa, this architectural masterpiece features panoramic ocean views, a private infinity pool, and state-of-the-art smart home integration.'
  },
  {
    _id: 'villa-2',
    title: 'The Imperial Sky Penthouse',
    location: 'Mumbai, Maharashtra',
    price: 240000000,
    propertyType: 'Penthouse',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 4,
    bathrooms: 5,
    floorSpace: '5,100',
    description: 'Perched high above the Mumbai skyline, The Imperial Sky Penthouse offers unmatched luxury, double-height ceilings, a private wrap-around terrace, and world-class bespoke interior finishes.'
  },
  {
    _id: 'villa-3',
    title: 'Palacio de Sol Contemporary Estate',
    location: 'Bengaluru, Karnataka',
    price: 125000000,
    propertyType: 'Luxury Villa',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 6,
    bathrooms: 7,
    floorSpace: '7,500',
    description: 'A sprawling sanctuary of modern architecture in Bengaluru. Palacio de Sol blends lush botanical gardens with sleek glass walls, offering private courtyards and resort-style living.'
  },
  {
    _id: 'villa-4',
    title: 'The Obsidian Grand Pinnacle',
    location: 'Delhi, New Delhi',
    price: 310000000,
    propertyType: 'Penthouse',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 5,
    bathrooms: 6,
    floorSpace: '6,800',
    description: 'Located in the heart of the capital, The Obsidian Grand Pinnacle redefines elite urban living with private elevator access, bullet-resistant glass accents, and custom Italian marble flooring.'
  },
  {
    _id: 'villa-5',
    title: 'Serene Haven Waterfront Villa',
    location: 'Kochi, Kerala',
    price: 95000000,
    propertyType: 'Luxury Villa',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 4,
    bathrooms: 4,
    floorSpace: '4,600',
    description: 'Immerse yourself in the tranquility of Kerala backwaters. This waterfront villa features private boat docking, traditional woodwork blended with modern comforts, and peaceful sunset views.'
  },
  {
    _id: 'villa-6',
    title: 'The Crown Jewel Sky Mansion',
    location: 'Hyderabad, Telangana',
    price: 160000000,
    propertyType: 'Penthouse',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 4,
    bathrooms: 5,
    floorSpace: '5,500',
    description: 'An architectural triumph in Hyderabad, offering panoramic views of the city, custom designer lighting, a private rooftop jacuzzi, and high-end security systems.'
  },
  {
    _id: 'villa-7',
    title: 'Elysian Hilltop Royal Villa',
    location: 'Udaipur, Rajasthan',
    price: 145000000,
    propertyType: 'Luxury Villa',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 5,
    bathrooms: 6,
    floorSpace: '6,100',
    description: 'Overlooking the historic lakes of Udaipur, Elysian Hilltop combines royal Rajasthani heritage aesthetics with ultra-modern luxury amenities and private courtyards.'
  },
  {
    _id: 'villa-8',
    title: 'Aura Glass Sanctuary Estate',
    location: 'Pune, Maharashtra',
    price: 110000000,
    propertyType: 'Luxury Villa',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 4,
    bathrooms: 5,
    floorSpace: '4,900',
    description: 'Designed around natural light and open-concept spaces, Aura Glass Sanctuary in Pune offers seamless indoor-outdoor living surrounded by serene green hills.'
  },
  {
    _id: 'villa-9',
    title: 'The Sovereign Presidential Penthouse',
    location: 'Kolkata, West Bengal',
    price: 190000000,
    propertyType: 'Penthouse',
    listingType: 'For Sale',
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80',
    bedrooms: 5,
    bathrooms: 6,
    floorSpace: '6,300',
    description: 'The epitome of elegance in Kolkata. Featuring expansive entertainment lounges, custom wood-paneled libraries, and elite skyline views.'
  }
];